// Presentation evidence only. Generated by scripts/prepare_case_study_evidence.py
// from the canonical exports and saved signal summary; tests detect source drift.
// Never import this module into cockpit selection or prioritization logic.
import evidence from './case-study-evidence.json'

export const caseStudyEvidence = evidence
